name: API Increment Version
on:
  push:
    branches: [ master ]
    paths: 
      - 'api/src/api/**'
      - '.github/workflows/api-build-and-publish.yaml'
      - '.github/workflows/api-eb-deploy.yaml'
jobs:
  build:
    name: Increment Version
    runs-on: ubuntu-latest

    steps: 
    - name: checkout
      uses: actions/checkout@v2
    - name: Increment version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0 # https://github.com/mathieudutour/github-tag-action
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        tag_prefix: 'api-'