name: API Deploy Elastic Beanstalk

on:
  workflow_run:
    workflows: ["Build and Publish to ECR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Bundle
        run: |
          export VERSION="latest"
          mkdir bundle
          envsubst < api/src/api/Dockerrun.aws.template.json > bundle/Dockerrun.aws.json
          cat bundle/Dockerrun.aws.json
          zip bundle.zip bundle
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # Thank you github https://github.com/aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::836386213271:role/AdminRole
          role-duration-seconds: 1200
        
      - run: echo "$GITHUB_ENV"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ env.AWS_SESSION_TOKEN }}
          application_name: big-todo-api
          environment_name: big-todo-api-d
          version_label: big-todo-latest
          region: us-east-1
          deployment_package: bundle.zip
  