name: API - Build and Publish to ECR

on:
  push:
    branches: [ master ]
    paths: 
      - 'api/src/api/**'
      - '.github/workflows/api-*'

jobs:
  api_increment_version:
    name: Increment Version
    runs-on: ubuntu-latest

    steps: 
    - name: checkout
      uses: actions/checkout@v2
    - name: Increment version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0 # https://github.com/mathieudutour/github-tag-action
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        tag_prefix: 'api-'
    
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}

  api_build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs: api_increment_version

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - run : echo ${{ needs.api_increment_version.outputs.tag }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1 # Thank you github https://github.com/aws-actions/configure-aws-credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::836386213271:role/AdminRole
        role-duration-seconds: 1200

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: big-todo-api
        IMAGE_TAG_LATEST: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_LATEST -f api/src/api/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_LATEST
