# https://betterprogramming.pub/ci-cd-for-flutter-apps-using-github-actions-b833f8f7aac
on:
  push:
    branches: [ master ]
    paths:
      - 'flutter-client/**'
      - '.github/workflows/flutter-build-and-release-apk.yaml'
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter-client
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '12.x'
        distribution: 'zulu'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.3'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.REPO_TOKEN }}