on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Create App Version
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.REPO_TOKEN }}